name: Send Dish Mail

on:
  push:
    branches:
      - 'master'
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - run: npm install
        env:
          NEIS_KEY: ${{ secrets.NEIS_KEY }}
          OFFICE_CODE: ${{ secrets.OFFICE_CODE }}
          SCHOOL_CODE: ${{ secrets.SCHOOL_CODE }}
          GOOGLE_EMAIL: ${{ secrets.GOOGLE_EMAIL }}
          GOOGLE_PW: ${{ secrets.GOOGLE_PW }}
      - run: npm run build
      - run: npm run start